name: hair_time
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.0.0

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.10.0
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  url_launcher: ^6.1.7
  go_router: ^11.1.4
  flutter_bloc: ^8.1.3
  provider: ^6.0.5
  flutter_localizations:
    sdk: flutter
  intl: any
  dropdown_button2: ^2.3.9
  dio: ^5.3.3
  build_runner: ^2.4.6

flutter_icons:
  image_path: "lib/assets/app_icon_bg.png"
  android: true
  ios: true
  adaptive_icon_background: "#63B5E9"
  adaptive_icon_foreground: "lib/assets/app_icon.png"
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - lib/assets/
    - lib/assets/font/
    - lib/assets/icon/

  fonts:
    - family: AnthonyHunter
      fonts:
        - asset: lib/assets/font/anthony_hunter.ttf
    - family: Raleway
      fonts:
        - asset: lib/assets/font/raleway_regular.ttf